# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=200, verbose_name='lijun'),
        ),
    ]
