# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170819_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(default='lijun', max_length=200),
        ),
    ]
